CREATE TABLE `clientes` (
`ClienteID` INT AUTO_INCREMENT,
`Nome` VARCHAR(50) NOT NULL,
`Email` VARCHAR(100) NULL DEFAULT NULL,
`telefone` VARCHAR(15) NULL DEFAULT NULL,
PRIMARY KEY(`ClienteID`) USING BTREE
)
