CREATE TABLE `midia` (
`MidiaID` INT AUTO_INCREMENT,
`FilmeID` INT,
`TipoMidia` VARCHAR(50) NOT NULL,
`Status` VARCHAR(10) NULL DEFAULT NULL,
PRIMARY KEY (`MidiaID`) USING BTREE,
FOREIGN KEY (`FilmeID`) REFERENCES filmes(`FilmeID`)
)